name: fth
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  analyzer: ^8.4.0
  path: ^1.9.1

dev_dependencies:
  flutter:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.6
